In [58]:
import numpy as np

# Now you can use np.array
#arr = np.array([1,2,3,4,5,5])
#arr


In [59]:
a = [2,3,4,"hello"]
a

[2, 3, 4, 'hello']

In [60]:
threeD = [[1,2,3] , [1,2,4] ,[3,54,5]]
np.array(threeD)

array([[ 1,  2,  3],
       [ 1,  2,  4],
       [ 3, 54,  5]])

In [61]:
# for array genrate like for loops 
arr = np.arange(1 , 11 )
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
# for genrate 0 array
#arr = np.zeros(9)
arr = np.zeros((3,4))# print matrices 3 rows and 4 column 
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
arr = np.ones((6,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
arr = np.linspace(0 , 1 , 10) # this is print between 0 to 1 10 number genrate 
arr 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [65]:
# Random Genration  function 
arr = np.random.rand(10)
arr

array([0.54822267, 0.62135634, 0.87435044, 0.15655847, 0.41007064,
       0.41116563, 0.38861007, 0.30901036, 0.1298694 , 0.31001374])

In [66]:
arr = np.random.randint(10 , 20 , 9) # that are print 9 random number between 10 to 20 
arr

array([17, 17, 18, 16, 10, 19, 12, 11, 11], dtype=int32)

In [67]:
#                       Array Atributes 
arr = np.array([[1,2,3] , [4,5,6] , [2,4,6]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [68]:
arr.shape # this is give the value row and column 

(3, 3)

In [69]:
arr.size # this is give the size

9

In [70]:
arr.dtype

dtype('int64')

In [71]:
#                       array Methods
arr

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [72]:
arr.min()

np.int64(1)

In [73]:
arr.max()

np.int64(6)

In [74]:
arr.sum()

np.int64(33)

In [75]:
arr.mean()

np.float64(3.6666666666666665)

In [76]:
arr.std()

np.float64(1.699673171197595)

In [77]:
arr.argmax()

np.int64(5)

In [78]:
arr.argmin()

np.int64(0)

In [79]:
#                                  REsahping and resizing 
arr = np.arange(1 , 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [80]:
arr.reshape(6 , 5)



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [81]:
arr = np.array([[1,2,3] , [2,3,4]])
arr.ndim # for idintify which dimensn arry

2

In [82]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [83]:
#       indexing and slicing matrix 
arr[1,4] # row and 5 column 

np.int64(10)

In [84]:
arr[3:6 , 3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [85]:
arr[:,2] # this is print cloumn

array([ 3,  8, 13, 18, 23, 28])

In [86]:
arr[:2] # this is print the row 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [88]:
#               bool Indexing 
arr = np.arange(1 , 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [90]:
arr[bool_index]

array([ 2,  4,  6,  8, 10, 12])