In [72]:
import numpy as np

In [73]:
# Array Arithmetic opreation

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2

array([ 7,  9, 11, 13, 15])

In [74]:
a1 - a2 # you can perform the many opreation Li +-*/ etc

array([-5, -5, -5, -5, -5])

In [75]:
#         broadcasting 
l = [10 , 20 ,30 ,40]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50])

In [76]:
#         deep and shallow copy
arr = np.arange(1 , 26) # ye apni alag copy abana lete hai ram me 
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [77]:
slice = arr[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [78]:
#matix opraeations
A = np.array([[1,2] , [4,5]]) # this is is 
B = np.array([[7,8] , [2,3]]) 


In [79]:
A  @ B # this is matrix multiplication 


array([[11, 14],
       [38, 47]])

In [80]:
# matrix transpose
A.T

array([[1, 4],
       [2, 5]])

In [81]:
# Advance Matrix opreation 
#   stacking in array 
# you can not stacked the matrix because theay have already
# you can stack  arrays

#A = np.array([1,2,3,4]) 
#B = np.array([5,6,7,8])
#np.vstack((A,B))
#np.hstack((A,B))
np.column_stack((A,B))



array([[1, 2, 7, 8],
       [4, 5, 2, 3]])

In [85]:
#   spillting the array 
arr = np.arange(16).reshape(4 , 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
np.hsplit(arr ,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [90]:
np.vsplit(arr ,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]